.PHONY: up down up-dev down-dev migrate generate-types composer-install setup-init setup-docker setup-local setup-finish

up:
	docker compose up -d --build --force-recreate

down:
	docker compose -f docker-compose.yml down

up-dev:
	docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build --force-recreate

down-dev:
	docker compose -f docker-compose.yml -f docker-compose.dev.yml down

migrate-up:
	docker compose exec php php local/modules/sprint.migration/tools/migrate.php config

generate-types:
	docker compose exec php /bin/sh -c "php bitrix/bitrix.php orm:annotate -m all"

composer-install:
	docker compose exec php /bin/sh -c "composer install"

setup-init:
	@bash scripts/init.sh
	
setup-docker:
	@chmod +x scripts/*.sh
	@bash scripts/setup-docker.sh

setup-local:
	@chmod +x scripts/*.sh
	@bash scripts/setup-local.sh

setup-finish:
	@chmod +x scripts/*.sh
	@bash scripts/post-install.sh
